spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/chaeum
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bium.chaeum.infrastructure.mybatis.record
#  해당 패키지 안에 있는 클래스들을 자동으로 스캔해서, 클래스 이름을 별칭(alias)으로 등록.
#  MyBatis의 XML 매퍼에서 parameterType, resultType 등을 지정할 때 클래스의 전체 경로 대신 별칭 사용.
#  ex)
  #  <select id="selectMeal" resultType="com.bium.chaeum.infrastructure.mybatis.record.Meal">
  #  -> <select id="selectMeal" resultType="Meal">
